config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  get 'employee', to: 'welcome#employee'

  resources :customers, only: [:new, :create, :update]
  resources :employees, only: [:show]

  namespace :api do
    namespace :v1 do
      post 'clockin', to: 'employees#clockin', defaults: { format: 'json' } 
      resources :vehicles, except: [:new, :edit], defaults: { format: 'json' }
      post '/vehicles/:id/pull_up', to: 'vehicles#pull_up'
      post '/vehicles/:id/give_quote', to: 'vehicles#give_quote'
      post '/vehicles/:id/return', to: 'vehicles#return'
    end
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :location
  has_one    :vehicle
  validates  :phone, length: { is: 10 }

  def send_code(phone_number)
    code = (1000..9999).to_a.sample
    self.text_confirmation = code
    self.save
    Messenger.send_code(phone_number, code)
  end

  def send_quote(quote)
    Messenger.send_quote(self.phone, quote)
  end

  def verify(customer, params, customer_params)
    if customer.text_confirmation == customer_params[:text_confirmation].to_i
      customer.location = Location.find(params["customer"]["location"])
      customer.vehicle = Vehicle.find_by(ticket_no: params["customer"]["ticket_no"]) 
      customer.save!
      customer.vehicle.status = "needs_quote"
      customer.vehicle.save
      customer.update!(customer_params)
      :final
    else
      :get_vehicle
    end
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validates :first_name, :last_name, :email, :password_digest, presence: true
  enum status: [ :active, :inactive ]
  belongs_to :location
  has_secure_password
  before_save :default_values
   
  def clockin(employee, params)
    if employee.authenticate(params["password"])
      employee.active!
      @response = { employee: employee, 
		    account:  employee.clockin_location(params),
		    vehicles: employee.clockin_location(params).vehicles 
      }
    else
      @response = { error: "auth failed" }     
    end
  end

  def clockin_location(clockin_params)
    Location.find_by(name: clockin_params["account"])
  end
  
  def default_values
    self.status ||= 'inactive'
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :vehicles
  has_many :employees
  validates :name, presence: true
end

app/models/messenger.rb
class Messenger

  def self.send_code(to, code)
    connection ||= Twilio::REST::Client.new(ENV['twilio_account_sid'], ENV['twilio_auth_token'])
    connection.account.messages.create({
      :from => ENV['twilio_number'],  
      :to => "+1#{to}",
      :body => "Your confirmation number is #{code}. Please continue on our mobile website."
    })
  end

  def self.send_quote(to, quote)
    connection ||= Twilio::REST::Client.new(ENV['twilio_account_sid'], ENV['twilio_auth_token'])
    connection.account.messages.create({
      :from => ENV['twilio_number'],  
      :to => "+1#{to}",
      :body => "Your vehicle will be ready in #{quote} minutes. Please try to be on time!"
    })
  end

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :location
  belongs_to :customer
  validates :ticket_no, length: { is: 3 }
  validates :space, presence: true
  before_save :default_values
  
  def default_values
    self.status ||= "parked"
  end

  def self.create_by_location(params)
    location = Location.find_by(name: params["account"])
    new_vehicle = location.vehicles.create(ticket_no: params["ticketNo"], 
					   space: params["space"], 
					   color: params["color"],
					   style: params["style"],
					   status: "parked"
					  )
  end

  def self.pull_up(params)
    vehicle = Vehicle.find(params["id"])
    vehicle.status = "transit"
    vehicle.save!
    vehicle
  end

  def self.give_quote(params)
    vehicle = Vehicle.find(params["id"])
    customer = Customer.find_by(ticket_no: params["ticket"])
    customer.send_quote(params["quote"])
    vehicle.status = "transit"
    vehicle.save!
    response = { vehicle: vehicle, quote: params["quote"] } 
  end

  def self.return(params)
    vehicle = Vehicle.find(params["id"])
    vehicle.status = "returned"
    vehicle.save
    vehicle
  end

end

app/controllers/api/v1/employees_controller.rb
class Api::V1::EmployeesController < ApiController
  def clockin
    employee = Employee.find_by(email: params["email"])
    respond_with (employee.clockin(employee, params)), location: root_url
  end
end

app/controllers/api/v1/vehicles_controller.rb
class Api::V1::VehiclesController < ApiController

  def index
    respond_with Location.find_by(name: params["account"]).vehicles, location: root_url
  end

  def create
    respond_with Vehicle.create_by_location(params), location: root_url
  end

  def pull_up
    respond_with Vehicle.pull_up(params), location: root_url
  end

  def give_quote
    respond_with Vehicle.give_quote(params), location: root_url
  end

  def return
    respond_with Vehicle.return(params), location: root_url
  end

end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  protect_from_forgery with: :null_session
  respond_to :json, :xml
  skip_before_filter :verify_authenticity_token
  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, PATCH, PUT, DELETE, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Origin, Content-Type, Accept, Authorization, Token'
    headers['Access-Control-Max-Age'] = "1728000"
  end

  def cors_preflight_check
    if request.method == 'OPTIONS'
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
      headers['Access-Control-Allow-Headers'] = 'Content-Type, X-Requested-With, X-Prototype-Version, Token'
      headers['Access-Control-Max-Age'] = '1728000'

      render :text => '', :content_type => 'text/plain'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.create(phone: customer_params[:phone])
    @customer.send_code(params["customer"]["phone"])

    render :get_vehicle
  end

  def update
    @customer = Customer.find(params[:id])
    render (@customer.verify(@customer, params, customer_params))
  end

  private

  def customer_params
    params.require(:customer).permit(:phone, :ticket_no, :text_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/final.html.erb
<div class="customer-final">
  <h1>Thank You!</h1>
  <h3>
    Your request has been sent. Soon you will
    recieve another text message including your
    valet fee and the amount of time until your 
    vehicle is ready for you. Please understand 
    that this time may vary from 2-20 minutes.
    <br>
    <br>
    Thank you for your cooperation!
  </h3>
  <p>
    If you enjoyed our service, click here to 
    see where else you can find us.
  </p>
</div>

app/views/customers/get_vehicle.html.erb
<div class="get-car-form">
<h1>Valet Information:</h1>
  <%= form_for @customer do |f| %>
    <h3>Location</h3>
    <%= f.collection_select(:location, Location.all, :id, :name ) %>
    <h3>Valet Ticket No.</h3>
    <%= f.text_field :ticket_no %>
    <h3>Text Message<br>Confirmation No.</h3>
    <%= f.text_field :text_confirmation, value: "" %>
    <br>
    <%= f.submit "I'm Ready" %>
  <% end %>
</div>

app/views/customers/new.html.erb
<h1 class="phone-request">Your mobile phone number:</h1>

<%= form_for @customer do |f| %>
  <%= f.number_field :phone, class: "phone" %>
  <%= f.submit "Last Step", class: "last-step" %>
<% end %>

<p>
  *We will send you a text-message to make sure you're real.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyCarPlease</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <div class="page-head">
    <h3><%= link_to "MCP", root_path %></h3>
  </div>
  <%= yield %>
</div>

</body>
</html>

app/views/welcome/employee.html.erb
<h1>Please Log in</h1>
<%= link_to "\"Login\"", "/employees/1" %>

app/views/welcome/index.html.erb
<div class="splash-wrap">
  <h2 class="text-center" >Getting your vehicle from valet is as easy as saying</h2> 
  <h1><%= button_to "\"Please\"", new_customer_path, method: :get, class: "btn" %></h1>
  <p>What is this?</p>
  <span class="glyphicon glyphicon-chevron-down"></span>
</div>
<div class="splash-scroll">
  <h3>
    My car please is a mobile web application that helps you communicate with valets.
    <br>
    <br>
    We keep you out of the snow, rain, and scorching heat by allowing you to easily request your vehicle with your smartphone.
    <br>
    <br>
    To initiate retrieval from a participating valet company, just click the "Please" button above.
  </h3>
</div>